describe("Assignment6", () => {
  it("tests Assignment6", () => {
    cy.viewport(1435, 136);
    cy.visit("http://studentweb.cencol.ca/wzhou60/COMP125/Assignment1/home.html");
    cy.get("nav > a:nth-of-type(2)").click();
    cy.location("href").should("eq", "http://studentweb.cencol.ca/wzhou60/COMP125/Assignment1/about.html");
    cy.get("button").click();
    cy.get("div a:nth-of-type(1)").click();
    cy.location("href").should("eq", "http://studentweb.cencol.ca/wzhou60/COMP125/Assignment1/calendar.html");
    cy.get("button").click();
    cy.get("div a:nth-of-type(2)").click();
    cy.location("href").should("eq", "http://studentweb.cencol.ca/wzhou60/COMP125/Assignment1/gallery.html");
    cy.get("img:nth-of-type(3)").click();
    cy.get("#addToFavorites").click();
    cy.get("img:nth-of-type(4)").click();
    cy.get("#lbOverlayClose").click();
    cy.get("section img").click();
    cy.get("main button").click();
    cy.get("div a:nth-of-type(3)").click();
    cy.location("href").should("eq", "http://studentweb.cencol.ca/wzhou60/COMP125/Assignment1/menulist.html");
    cy.get("nav > a:nth-of-type(3)").click();
    cy.location("href").should("eq", "http://studentweb.cencol.ca/wzhou60/COMP125/Assignment1/order.html");
    cy.get("#item1").click();
    cy.get("#item1").type("1");
    cy.get("#item1").type("2");
    cy.get("#item1").dblclick();
    cy.get("#item1").type("3");
    cy.get("#item1").click();
    cy.get("#item1").type("4");
    cy.get("#item1").click();
    cy.get("#item2").type("1");
    cy.get("#item2").type("2");
    cy.get("#item2").dblclick();
    cy.get("#item2").type("3");
    cy.get("#item2").click();
    cy.get("a:nth-of-type(4)").click();
    cy.location("href").should("eq", "http://studentweb.cencol.ca/wzhou60/COMP125/Assignment1/location.html");
    cy.get("a:nth-of-type(5)").click();
    cy.location("href").should("eq", "http://studentweb.cencol.ca/wzhou60/COMP125/Assignment1/contact.html");
    cy.get("#name").click();
    cy.get("#name").type("J");
    cy.get("#name").type("Jackie");
    cy.get("#email").type("wzhou60@my.centennialcollege.ca");
    cy.get("#message").click();
    cy.get("#message").type("Hello");
    cy.get("main button").click();
    cy.location("href").should("eq", "http://studentweb.cencol.ca/wzhou60/COMP125/Assignment1/contact.html?name=Jackie&email=wzhou60%40my.centennialcollege.ca&message=Hello");
    cy.get("a:nth-of-type(6)").click();
    cy.location("href").should("eq", "http://studentweb.cencol.ca/wzhou60/COMP125/Assignment1/assignment4.html");
    cy.get("#fname").click();
    cy.get("#fname").type("Jax");
    cy.get("#lname").type("Zed");
    cy.get("#email").type("dillcheese1@gmail.com");
    cy.get("#age").click();
    cy.get("#age").type("22");
    cy.get("#postalCode").click();
    cy.get("#postalCode").type("M1T2v1");
    cy.get("#province").type("QC");
    cy.get("#province").click();
    cy.get("#province").type("ON");
    cy.get("#password").click();
    cy.get("#password").type("Q");
    cy.get("#password").type("Qwert123");
    cy.get("#confirmPassword").type("qwert123");
    cy.get("#register").click();
    cy.get("#confirmPassword").dblclick();
    cy.get("#confirmPassword").click();
    cy.get("#confirmPassword").type("Q");
    cy.get("#confirmPassword").type("Qwert123");
    cy.get("#password").dblclick();
    cy.get("#password").click();
    cy.get("#password").type("Q");
    cy.get("#password").type("Qwert123");
    cy.get("#register").click();
    cy.get("a:nth-of-type(7)").click();
    cy.location("href").should("eq", "http://studentweb.cencol.ca/wzhou60/COMP125/Assignment1/sitemap.html");
  });
});
//# recorderSourceMap=BCBDBECGBHCJBKCMBNBOBPBQBRBSCUCWBXBYBZBaBbBcBdBeBfBgBBhBBiBBjBClBCnBBoBBpBApBBqBAqBAqBBrBBsBBtBCvBCxBByBBzBB0BB1BB2BB3BB4BB5BB6BB7BB8BB9BB+BA+BB/BA/BA/BA/BA/BBgCBhCBiCBjCBkCAkCBlCBmCBnCBoCAoCBpCBqCC
