describe("Restaurants", () => {
  it("tests Restaurants", () => {
    cy.viewport(1594, 217);
    cy.visit("http://127.0.0.1:5500/Assignment1/home.html");
    cy.get("nav > a:nth-of-type(2)").click();
    cy.location("href").should("eq", "http://127.0.0.1:5500/Assignment1/about.html");
    cy.get("button").click();
    cy.get("div a:nth-of-type(1)").click();
    cy.location("href").should("eq", "http://127.0.0.1:5500/Assignment1/calendar.html");
    cy.get("div a:nth-of-type(2)").click();
    cy.location("href").should("eq", "http://127.0.0.1:5500/Assignment1/gallery.html");
    cy.get("img:nth-of-type(3)").click();
    cy.get("#addToFavorites").click();
    cy.get("section img").click();
    cy.get("#favorites > div").click();
    cy.get("main button").click();
    cy.get("div a:nth-of-type(3)").click();
    cy.location("href").should("eq", "http://127.0.0.1:5500/Assignment1/menulist.html");
    cy.get("div:nth-of-type(3) > img").click();
    cy.get("nav > a:nth-of-type(3)").click();
    cy.location("href").should("eq", "http://127.0.0.1:5500/Assignment1/order.html");
    cy.get("#item1").type("1");
    cy.get("#item1").click();
    cy.get("#item1").type("2");
    cy.get("#item1").click();
    cy.get("a:nth-of-type(4)").click();
    cy.location("href").should("eq", "http://127.0.0.1:5500/Assignment1/location.html");
    cy.get("a:nth-of-type(5)").click();
    cy.location("href").should("eq", "http://127.0.0.1:5500/Assignment1/contact.html");
    cy.get("#name").click();
    cy.get("#name").type("JA");
    cy.get("#name").type("JAc");
    cy.get("#email").type("jzhou39@gmail.com");
    cy.get("#message").type("");
    cy.get("#message").click();
    cy.get("#message").type("Hello");
    cy.get("main button").click();
    cy.location("href").should("eq", "http://127.0.0.1:5500/Assignment1/contact.html?name=JAc&email=jzhou39%40gmail.com&message=Hello");
    cy.get("a:nth-of-type(6)").click();
    cy.location("href").should("eq", "http://127.0.0.1:5500/Assignment1/assignment4.html");
    cy.get("#fname").click();
    cy.get("#fname").type("Jackie");
    cy.get("#lname").type("Zhou)");
    cy.get("#email").type("jzhou39@gmail.com");
    cy.get("#age").type("22");
    cy.get("#postalCode").type("L3S2M5");
    cy.get("#province").type("ON");
    cy.get("#password").type("");
    cy.get("#confirmPassword").type("");
    cy.get("#lname").click();
    cy.get("#lname").type("Zhou");
    cy.get("main").click();
    cy.get("#password").click();
    cy.get("#password").type("L");
    cy.get("#password").type("Lordmole123");
    cy.get("#confirmPassword").type("L");
    cy.get("#confirmPassword").type("Lordmole123");
    cy.get("#register").click();
    cy.get("#reg-form").click();
    cy.get("a:nth-of-type(7)").click();
    cy.location("href").should("eq", "http://127.0.0.1:5500/Assignment1/sitemap.html");
  });
});
//# recorderSourceMap=BCBDBECGBHCJCLBMBNBOBPBQCSBTCVBWBXBYBZCbCdBeBfAfBgBAgBAgBBhBBiBBjBBkBCmBCoBBpBBqBBrBBsBBtBBuBBvBBwBBxBByBAyBAyBBzBB0BB1BB2BA2BB3BA3BA3BB4BA4BB5BB6BB7BC
